/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Building(props) {
  const { nodes, materials } = useGLTF('/models/building-transformed.glb')
  
  return (
    <group {...props} dispose={null}>
      <group position={[...props.position]} scale={0.07} rotation={[Math.PI / 2, 0, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Build11_obj_1.geometry}>
          <meshPhongMaterial color={'#222222'} />
        </mesh>
        <mesh castShadow receiveShadow geometry={nodes.Build11_obj_2.geometry}>
          <meshStandardMaterial color={'#fff'} emissive={'yellow'} emissiveIntensity={.9} toneMapped={false}  />
        </mesh>
        <mesh castShadow receiveShadow geometry={nodes.Build11_obj_3.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

// useGLTF.preload('/models/building-transformed.glb')

export default Building