/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Streetlight_Model(props) {
  const { nodes, materials } = useGLTF('/models/streetlight-transformed.glb')

  return (
    <group {...props} dispose={null} scale={0.07}>
      <mesh castShadow receiveShadow geometry={nodes.streetlight.geometry} material={materials.Build11} />
    </group>
  )
}

// useGLTF.preload('/models/streetlight-transformed.glb')

export default Streetlight_Model