/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'
// import { Object3D } from "three"

import Sound from './Sound'

function Car(props) {
  const [sound, setSound] = useState(null)
  const [parked, setParked] = useState(false)

  const { nodes, materials } = useGLTF('/models/car-transformed.glb')
  
  const ref = useRef()
  const lightRef1 = useRef()
  const lightRef2 = useRef()
  const targetRef1 = useRef(new THREE.Object3D)
  const targetRef2 = useRef(new THREE.Object3D)

  const carVector = new THREE.Vector3(...[1, 0, -2.5])

  useEffect(() => {
    if(!sound){
      setSound(
        <Sound 
          url={'./sounds/take_five.mp3'} 
        />
      )
    }
  }, [])

  useEffect(() => {
    setParked(props.parked)
  }, [props.parked])
  

  useFrame(() => {
    if(!parked){
      if(ref.current.position.x < 100){
        ref.current.position.x += 0.15
      } else {
        ref.current.position.x = -100
      }
    } else {
      if((ref.current.position.x <= .9 || ref.current.position.x >= 1.1)  && ref.current.position.z >= -2.5){
        ref.current.position.lerp(carVector, .03)
      }
    }

    // headlights
    const lightPos = new THREE.Vector3(...ref.current.position)
    lightRef1.current.target = targetRef1.current

    lightPos.z = ref.current.position.z + 0.2
    lightPos.x = ref.current.position.x + 5

    lightRef1.current.target.position.set(...lightPos)
    lightRef1.current.target.updateMatrixWorld()

    const lightPos2 = new THREE.Vector3(...ref.current.position)
    
    lightRef2.current.target = targetRef2.current

    lightPos2.z = ref.current.position.z - 0.2
    lightPos2.x = ref.current.position.x + 5

    lightRef2.current.target.position.set(...lightPos2)
    lightRef2.current.target.updateMatrixWorld()
  })
  
  return (
    <group {...props} position={[-100, 0, -2]} ref={ref} dispose={null} scale={0.7} rotation={[0, 90*Math.PI/180, 0]}>
      <mesh castShadow receiveShadow geometry={nodes.Circle072.geometry}>
        <meshPhongMaterial color={'#222222'} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.Circle072_1.geometry}>
        <meshStandardMaterial color={'#fff'} emissive={'yellow'} emissiveIntensity={10} toneMapped={false} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.Circle072_2.geometry}>
        <meshStandardMaterial color={'#e7e7e7'} transparent opacity={0.05} />
      </mesh>

      <spotLight ref={lightRef1} castShadow penumbra={0} distance={10} angle={0.2} attenuation={5} anglePower={4} intensity={20}  position={[-0.7, 0.4, .2]} color={'yellow'} />
      <spotLight ref={lightRef2} castShadow penumbra={0} distance={10} angle={0.2} attenuation={5} anglePower={4} intensity={20}  position={[0.9, 0.4, .2]} color={'yellow'} />
    
      {props.audio && sound}
    </group>
  )
}

// useGLTF.preload('/models/car-transformed.glb')

export default Car
