/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

function NewspaperStand_Model(props) {
  const { nodes, materials } = useGLTF('/models/newspaperVending-transformed.glb')

  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cube_1.geometry} material={materials['Material.003']} />

      <mesh castShadow receiveShadow geometry={nodes.Cube_2.geometry}>
        <meshStandardMaterial color={'#e7e7e7'} transparent opacity={0.1} />
      </mesh>

      <mesh castShadow receiveShadow geometry={nodes.Cube_3.geometry} material={materials.paperVendGlassCol} />
      <mesh castShadow receiveShadow geometry={nodes.Cube_4.geometry} material={materials.venderMetal} />
    </group>
  )
}

// useGLTF.preload('/newspaperVending-transformed.glb')

export default NewspaperStand_Model